---
- hosts: prod-server
  become: true
  tasks:
  - name: update apt
    command: sudo yum update

  - name: install docker
    command: sudo yum install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker
  
  - name: stop and remove existing insure-me container
    command: sudo docker rm -f insure-me 
    
  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me praveensirvi/insure-me:v3
